name: expressjs-server-boilerplate
services:
  expressjs:
    build:
      context: .
    ports:
      - "3000:3000"   # локально на Маке будет доступно :3001
    env_file:
      - .env.local          # если нужны секреты/переменные
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:${PORT}/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
